### ISSUE TITLE
Pdist interpretation

### ISSUE THREAD

**Issue by chauvenne** [Tristanovsk/coxmunk#1]
Dear @Tristanovsk,

Thank you for this open-source projet.

I have some troubles interpreting the Pdist value.
Is this the probability for a point on the sea surface to have the corresponding wave slope in the "tolerance ellipse"? i.e. this point would have some probability to reflect towards the sensor?

Thanks in advance!

**Comment by Tristanovsk** [comment]
Dear Rémi,
The Pdist value is the proportion of the conceptual wave facets having the good orientation to produce direct sunlight reflection for a given viewing geometry. Pdist can be computed following several statistical models (e.g., Cox-Munk, Bréon-Henriot).
